apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minilinux-deployment
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-user/your-repo
    targetRevision: HEAD
    path: minilinux-chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
