{{- $root := . }}
{{- $count := int .Values.students }}
{{- range $i := seq $count }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-{{ $i }}
  labels:
    app: dvwa-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-{{ $i }}
  template:
    metadata:
      labels:
        app: dvwa-{{ $i }}
    spec:
      containers:
        - name: dvwa
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          ports:
            - containerPort: 80
---
{{- end }}
