{{- $names := .Values.students }}
{{- $count := .Values.studentCount | int }}
{{- range $i := until $count }}
{{- $name := index $names $i | default (printf "student%d" $i) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-{{ $name }}
  labels:
    app: dvwa-{{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-{{ $name }}
  template:
    metadata:
      labels:
        app: dvwa-{{ $name }}
    spec:
      containers:
        - name: dvwa
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          ports:
            - containerPort: 80
---
{{- end }}
