{{- $root  := . }}
{{- $count := int .Values.students }}        # $count is a Go int
{{- $stop  := (add $count 1) | int }}       # compute count+1, cast back to int
{{- range $i := untilStep 1 $stop 1 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-student{{ $i }}-ingress
  namespace: {{ $root.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: student{{ $i }}.zeneli.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dvwa-svc-{{ $i }}
                port:
                  number: 80
{{- end }}
