{{- $root := . }}
{{- $studentCount := int $root.Values.students }}
{{- range $i := until $studentCount }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-student{{ $i + 1 }}-ingress
  namespace: {{ $root.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: student{{ $i + 1 }}.zeneli.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dvwa-svc-{{ $i + 1}}
                port:
                  number: 80
---
{{- end }}
