{{- range $i := until .Values.students }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-student{{ $i }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: student{{ $i }}.zeneli.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dvwa-svc-{{ $i }}
                port:
                  number: 80
---
{{- end }}
