{{- $root := . }}
{{- $studentCount := int $root.Values.students }}
{{- range $i := untilStep 1 (add $studentCount 1) 1 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa-student{{ $i }}-ingress
  namespace: {{ $root.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: student{{ $i }}.zeneli.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dvwa-svc-{{ $i }}
                port:
                  number: 80
---
{{- end }}
