{{- $names := .Values.students }}
{{- $count := .Values.studentCount | int }}
{{- range $i := until $count }}
{{- $name := index $names $i | default (printf "student%d" $i) }}
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-svc-{{ $name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $name }}.dvwaapplicatie.com.
spec:
  type: LoadBalancer
  selector:
    app: dvwa-{{ $name }}
  ports:
    - port: 80
      targetPort: 80
---
{{- end }}
