{{- $root := . }}
{{- $studentCount := int $root.Values.students }}
{{- range $i := untilStep 1 (add $studentCount 1) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-svc-{{ $i }}
spec:
  type: LoadBalancer
  selector:
    app: dvwa-{{ $i }}
  ports:
    - port: 80
      targetPort: 80
---
{{- end }}
