apiVersion: v1
kind: Service
metadata:
  name: minilinux-service
spec:
  selector:
    app: minilinux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
