apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvwa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Purpolel/PoC_k3s'
    targetRevision: HEAD
    path: charts/dvwa
    helm:
      createNamespace: true   # ← this makes ArgoCD create *any* namespace you set below
      parameters: []

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dvwa          # ← this field is dynamic: change it in the GUI/YAML per-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
