apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvwa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/YourOrg/PoC_k3s'
    targetRevision: HEAD
    path: charts/dvwa
    helm:
      parameters: []

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dvwa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
