apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minilinux-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Purpolel/PoC_k3s'  
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
